flowchart LR
  subgraph HELP_SCREEN [HELP SCREEN]
    SCREEN_HELP_TEXT["
      Бот помогает учить сербский язык
      (и может быть английский)
      Для изучения используются flash карточки,
      которые состоят из картинки, шкалы прогресса,
      текста и набора кнопок
      Частота отображения карточек зависит от того
      насколько хорошо они изучены.
      В первую очередь отображаются карточки которые
      пока вызывают сложности, потом новые,
      а после них хорошо изученные
      Для оценки своего прогресса нажмите на одну
      из кнопок с цветными маркерами
      🔴 ??? – Фраза на карточке совершенно непонятна
      🟡 Hard – Трудно вспомнить, как сказать фразу,
      забытые некоторые слова или грамматические конструкции
      🟢 Ok – Фраза понятна и вспоминается без особого труда
      🔵 Easy – Всё очень просто, фраза известна и понятна
      ❌ Hide – Можете убрать карточку, которая вам
      не нравится или хорошо изучена.
      Больше Вы её не увидите
      ⏩ Skip – Пропустить карточку

      Карточки показываются пачками по 20 штук.
      После каждой пачки отображается статистика
      за сегодняший и 4 предыдущих дня
    "]
  end

  subgraph START_SCREEN [START SCREEN]
    SCREEN_START_TEXT["Бот помогает учить сербский язык,\nиспользуя flash cards"]
    BUTTON_LEARN["Учить карточки"]:::class_button
    BUTTON_STAT["Статистика"]:::class_button
    BUTTON_HELP["Подробная справка"]:::class_button
  end

  subgraph LEARN_SCREEN [LEARN SCREEN]
    direction LR
    subgraph LEARN_SCREEN_IMAGE [LEARN SCREEN IMAGE]
      IMAGE["<Скрытая картинка>"]
    end
    subgraph LEARN_SCREEN_PROGRESS [LEARN SCREEN PROGRESS]
      PROGRESS["<Прогресс изучения карточки>"]
    end
    subgraph LEARN_SCREEN_BUTTONS_ROW1 [" "]
      ???
      Hard
      Ok
      Easy
    end
  end

BUTTON_HELP -.-> HELP_SCREEN
BUTTON_LEARN -.-> LEARN_SCREEN

%% style SCREEN_HELP_TEXT width: 400px, text-oveflow: hidden

style SCREEN_START_TEXT text-align: left;
style SCREEN_HELP_TEXT text-align: left;

style LEARN_SCREEN_IMAGE width: 400px;
style LEARN_SCREEN_PROGRESS width: 400px;

classDef class_button color: blue;

