block-beta
  block:SCREEN_START
    columns 1
    block
      SCREEN_START_TEXT["Бот помогает учить сербский язык,\nиспользуя flash cards"]
    end
    block
      columns 2
      BUTTON_LEARN["Учить карточки"] BUTTON_STAT["Статистика"]
      BUTTON_HELP["Подробная справка"]
    end
  end

style SCREEN_START_TEXT text-align: left
